# Generated by Django 3.2 on 2022-05-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_staft',
            new_name='is_staff',
        ),
    ]
